# Generated by Django 2.1.5 on 2019-01-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0003_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('article', models.ManyToManyField(to='MYBLOG.Post')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYBLOG.Profile')),
            ],
        ),
    ]
