# Generated by Django 2.1.5 on 2019-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='dave.com', max_length=50),
            preserve_default=False,
        ),
    ]
