# Generated by Django 2.1.5 on 2019-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0005_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.gpg', null=True, upload_to='profile_pics'),
        ),
    ]
