# Generated by Django 2.1.5 on 2019-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0006_auto_20190112_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
